### ISSUE TITLE
Attach data nama dan harga menu di button

### ISSUE THREAD

**Issue by ImBobby** [sebastianusbara/shop#1]
Data nama dan harga menu lebih baik di-attach di button.

``` HTML
<button
    class="box__button box__button--blue"
    data-nama="Semur Jengkol"
    data-harga="15000">
    Add to Cart
</button>
```

karena yang kamu buat sekarang sangat rentan pada saat ada perubahan struktur markup. Ke depannya apabila nama dan harga bukan lagi siblings dari button, kamu harus mengubah codingan JS kamu.

**Comment by sebastianusbara** [comment]
cool, thanks banget tipsnya mas

Pada 21 Desember 2015 14.30, Bobby notifications@github.com menulis:
